// <auto-generated />
using System;
using DktApi.Models.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DktApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416110801_Baseline")]
    partial class Baseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DktApi.Models.Db.AssetSet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AssetJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asset_json");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_id");

                    b.Property<long>("LetterId")
                        .HasColumnType("bigint")
                        .HasColumnName("letter_id");

                    b.HasKey("Id");

                    b.HasIndex("LetterId");

                    b.HasIndex("GameId", "LetterId")
                        .IsUnique();

                    b.ToTable("asset_sets");
                });

            modelBuilder.Entity("DktApi.Models.Db.DifficultyLevel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("difficulty_levels");
                });

            modelBuilder.Entity("DktApi.Models.Db.Feedback", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("GameSessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_session_id");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<long>("TherapistId")
                        .HasColumnType("bigint")
                        .HasColumnName("therapist_id");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("TherapistId");

                    b.ToTable("feedback");
                });

            modelBuilder.Entity("DktApi.Models.Db.Game", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("DifficultyLevelId")
                        .HasColumnType("bigint")
                        .HasColumnName("difficulty_level_id");

                    b.Property<long>("GameTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_type_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyLevelId");

                    b.HasIndex("GameTypeId");

                    b.ToTable("games");
                });

            modelBuilder.Entity("DktApi.Models.Db.GameSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AssetSetId")
                        .HasColumnType("bigint")
                        .HasColumnName("asset_set_id");

                    b.Property<int?>("DurationSec")
                        .HasColumnType("integer")
                        .HasColumnName("duration_sec");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_id");

                    b.Property<long>("LetterId")
                        .HasColumnType("bigint")
                        .HasColumnName("letter_id");

                    b.Property<int>("MaxScore")
                        .HasColumnType("integer")
                        .HasColumnName("max_score");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<long?>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_id");

                    b.HasKey("Id");

                    b.HasIndex("AssetSetId");

                    b.HasIndex("GameId");

                    b.HasIndex("LetterId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TaskId");

                    b.ToTable("game_sessions");
                });

            modelBuilder.Entity("DktApi.Models.Db.GameSessionItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("GameSessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_session_id");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("item_type");

                    b.Property<int>("OrderNo")
                        .HasColumnType("integer")
                        .HasColumnName("order_no");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt_text");

                    b.Property<int?>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.ToTable("game_session_items");
                });

            modelBuilder.Entity("DktApi.Models.Db.GameType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("game_types");
                });

            modelBuilder.Entity("DktApi.Models.Db.Letter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("display_name");

                    b.HasKey("Id");

                    b.ToTable("letters");
                });

            modelBuilder.Entity("DktApi.Models.Db.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<long>("TherapistId")
                        .HasColumnType("bigint")
                        .HasColumnName("therapist_id");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TherapistId");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("DktApi.Models.Db.Player", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Abouts")
                        .HasColumnType("text")
                        .HasColumnName("abouts");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<string>("City")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("city");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Diagnosis")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("diagnosis");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("gender");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nickname");

                    b.Property<string>("ParentName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("parent_name");

                    b.Property<string>("ParentPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("parent_phone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("SchoolName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("school_name");

                    b.Property<int?>("TotalScore")
                        .HasColumnType("integer")
                        .HasColumnName("total_score");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("players");
                });

            modelBuilder.Entity("DktApi.Models.Db.TaskItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AssetSetId")
                        .HasColumnType("bigint")
                        .HasColumnName("asset_set_id");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<DateTime?>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_id");

                    b.Property<long>("LetterId")
                        .HasColumnType("bigint")
                        .HasColumnName("letter_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<long>("TherapistId")
                        .HasColumnType("bigint")
                        .HasColumnName("therapist_id");

                    b.HasKey("Id");

                    b.HasIndex("AssetSetId");

                    b.HasIndex("GameId");

                    b.HasIndex("LetterId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TherapistId");

                    b.ToTable("tasks");
                });

            modelBuilder.Entity("DktApi.Models.Db.Therapist", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("ClinicName")
                        .HasColumnType("text")
                        .HasColumnName("clinic_name");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("text")
                        .HasColumnName("license_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("profile_image_url");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("therapists");
                });

            modelBuilder.Entity("DktApi.Models.Db.TherapistClient", b =>
                {
                    b.Property<long>("TherapistId")
                        .HasColumnType("bigint")
                        .HasColumnName("therapist_id");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.HasKey("TherapistId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("therapist_clients");
                });

            modelBuilder.Entity("DktApi.Models.Db.AssetSet", b =>
                {
                    b.HasOne("DktApi.Models.Db.Game", "Game")
                        .WithMany("AssetSets")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DktApi.Models.Db.Letter", "Letter")
                        .WithMany("AssetSets")
                        .HasForeignKey("LetterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Letter");
                });

            modelBuilder.Entity("DktApi.Models.Db.Feedback", b =>
                {
                    b.HasOne("DktApi.Models.Db.GameSession", "GameSession")
                        .WithMany("Feedbacks")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DktApi.Models.Db.Therapist", "Therapist")
                        .WithMany("Feedbacks")
                        .HasForeignKey("TherapistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("Therapist");
                });

            modelBuilder.Entity("DktApi.Models.Db.Game", b =>
                {
                    b.HasOne("DktApi.Models.Db.DifficultyLevel", "DifficultyLevel")
                        .WithMany("Games")
                        .HasForeignKey("DifficultyLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DktApi.Models.Db.GameType", "GameType")
                        .WithMany("Games")
                        .HasForeignKey("GameTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DifficultyLevel");

                    b.Navigation("GameType");
                });

            modelBuilder.Entity("DktApi.Models.Db.GameSession", b =>
                {
                    b.HasOne("DktApi.Models.Db.AssetSet", "AssetSet")
                        .WithMany("GameSessions")
                        .HasForeignKey("AssetSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DktApi.Models.Db.Game", "Game")
                        .WithMany("GameSessions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DktApi.Models.Db.Letter", "Letter")
                        .WithMany("GameSessions")
                        .HasForeignKey("LetterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DktApi.Models.Db.Player", "Player")
                        .WithMany("GameSessions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DktApi.Models.Db.TaskItem", "Task")
                        .WithMany("GameSessions")
                        .HasForeignKey("TaskId");

                    b.Navigation("AssetSet");

                    b.Navigation("Game");

                    b.Navigation("Letter");

                    b.Navigation("Player");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("DktApi.Models.Db.GameSessionItem", b =>
                {
                    b.HasOne("DktApi.Models.Db.GameSession", "GameSession")
                        .WithMany("Items")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("DktApi.Models.Db.Notification", b =>
                {
                    b.HasOne("DktApi.Models.Db.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DktApi.Models.Db.Therapist", "Therapist")
                        .WithMany()
                        .HasForeignKey("TherapistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Therapist");
                });

            modelBuilder.Entity("DktApi.Models.Db.TaskItem", b =>
                {
                    b.HasOne("DktApi.Models.Db.AssetSet", "AssetSet")
                        .WithMany("Tasks")
                        .HasForeignKey("AssetSetId");

                    b.HasOne("DktApi.Models.Db.Game", "Game")
                        .WithMany("Tasks")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DktApi.Models.Db.Letter", "Letter")
                        .WithMany("Tasks")
                        .HasForeignKey("LetterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DktApi.Models.Db.Player", "Player")
                        .WithMany("Tasks")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DktApi.Models.Db.Therapist", "Therapist")
                        .WithMany("Tasks")
                        .HasForeignKey("TherapistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetSet");

                    b.Navigation("Game");

                    b.Navigation("Letter");

                    b.Navigation("Player");

                    b.Navigation("Therapist");
                });

            modelBuilder.Entity("DktApi.Models.Db.TherapistClient", b =>
                {
                    b.HasOne("DktApi.Models.Db.Player", "Player")
                        .WithMany("TherapistClients")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DktApi.Models.Db.Therapist", "Therapist")
                        .WithMany("TherapistClients")
                        .HasForeignKey("TherapistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Therapist");
                });

            modelBuilder.Entity("DktApi.Models.Db.AssetSet", b =>
                {
                    b.Navigation("GameSessions");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("DktApi.Models.Db.DifficultyLevel", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("DktApi.Models.Db.Game", b =>
                {
                    b.Navigation("AssetSets");

                    b.Navigation("GameSessions");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("DktApi.Models.Db.GameSession", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("DktApi.Models.Db.GameType", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("DktApi.Models.Db.Letter", b =>
                {
                    b.Navigation("AssetSets");

                    b.Navigation("GameSessions");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("DktApi.Models.Db.Player", b =>
                {
                    b.Navigation("GameSessions");

                    b.Navigation("Tasks");

                    b.Navigation("TherapistClients");
                });

            modelBuilder.Entity("DktApi.Models.Db.TaskItem", b =>
                {
                    b.Navigation("GameSessions");
                });

            modelBuilder.Entity("DktApi.Models.Db.Therapist", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Tasks");

                    b.Navigation("TherapistClients");
                });
#pragma warning restore 612, 618
        }
    }
}
