using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DktApi.Migrations
{
    /// <inheritdoc />
    public partial class AddInvitationAndConnectionRequest : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Tablolar daha önce manuel SQL ile oluşturulmuş olabileceğinden
            // IF NOT EXISTS kullanarak idempotent hale getiriyoruz.
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS invitation_codes (
                    id bigint GENERATED BY DEFAULT AS IDENTITY,
                    code character varying(8) NOT NULL,
                    therapist_id bigint NOT NULL,
                    status character varying(20) NOT NULL DEFAULT 'PENDING',
                    created_at timestamp with time zone NOT NULL,
                    expires_at timestamp with time zone NOT NULL,
                    used_at timestamp with time zone,
                    used_by_player_id bigint,
                    CONSTRAINT ""PK_invitation_codes"" PRIMARY KEY (id),
                    CONSTRAINT ""FK_invitation_codes_players_used_by_player_id""
                        FOREIGN KEY (used_by_player_id) REFERENCES players (id),
                    CONSTRAINT ""FK_invitation_codes_therapists_therapist_id""
                        FOREIGN KEY (therapist_id) REFERENCES therapists (id) ON DELETE CASCADE
                );
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS connection_requests (
                    id bigint GENERATED BY DEFAULT AS IDENTITY,
                    player_id bigint NOT NULL,
                    therapist_id bigint NOT NULL,
                    invitation_id bigint NOT NULL,
                    status character varying(20) NOT NULL DEFAULT 'PENDING',
                    created_at timestamp with time zone NOT NULL,
                    responded_at timestamp with time zone,
                    CONSTRAINT ""PK_connection_requests"" PRIMARY KEY (id),
                    CONSTRAINT ""FK_connection_requests_invitation_codes_invitation_id""
                        FOREIGN KEY (invitation_id) REFERENCES invitation_codes (id) ON DELETE CASCADE,
                    CONSTRAINT ""FK_connection_requests_players_player_id""
                        FOREIGN KEY (player_id) REFERENCES players (id) ON DELETE CASCADE,
                    CONSTRAINT ""FK_connection_requests_therapists_therapist_id""
                        FOREIGN KEY (therapist_id) REFERENCES therapists (id) ON DELETE CASCADE
                );
            ");

            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_connection_requests_invitation_id"" ON connection_requests (invitation_id);");
            migrationBuilder.Sql(@"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_connection_requests_player_id_therapist_id"" ON connection_requests (player_id, therapist_id);");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_connection_requests_therapist_id"" ON connection_requests (therapist_id);");
            migrationBuilder.Sql(@"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_invitation_codes_code"" ON invitation_codes (code);");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_invitation_codes_therapist_id"" ON invitation_codes (therapist_id);");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_invitation_codes_used_by_player_id"" ON invitation_codes (used_by_player_id);");
        }


        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS connection_requests;");
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS invitation_codes;");
        }
    }
}
